// Enthält alle Länder mit Hauptstadt, Emoji und Kontinent
const countries = [
  { name: "Afghanistan", capital: "Kabul", flag: "🇦🇫", continent: "Asia" },
  { name: "Albania", capital: "Tirana", flag: "🇦🇱", continent: "Europe" },
  { name: "Algeria", capital: "Algiers", flag: "🇩🇿", continent: "Africa" },
  { name: "Andorra", capital: "Andorra la Vella", flag: "🇦🇩", continent: "Europe" },
  { name: "Angola", capital: "Luanda", flag: "🇦🇴", continent: "Africa" },
  { name: "Antigua and Barbuda", capital: "Saint John's", flag: "🇦🇬", continent: "North America" },
  { name: "Argentina", capital: "Buenos Aires", flag: "🇦🇷", continent: "South America" },
  { name: "Armenia", capital: "Yerevan", flag: "🇦🇲", continent: "Asia" },
  { name: "Australia", capital: "Canberra", flag: "🇦🇺", continent: "Oceania" },
  { name: "Austria", capital: "Vienna", flag: "🇦🇹", continent: "Europe" },
  { name: "Azerbaijan", capital: "Baku", flag: "🇦🇿", continent: "Asia" },
  { name: "Bahamas", capital: "Nassau", flag: "🇧🇸", continent: "North America" },
  { name: "Bahrain", capital: "Manama", flag: "🇧🇭", continent: "Asia" },
  { name: "Bangladesh", capital: "Dhaka", flag: "🇧🇩", continent: "Asia" },
  { name: "Barbados", capital: "Bridgetown", flag: "🇧🇧", continent: "North America" },
  { name: "Belarus", capital: "Minsk", flag: "🇧🇾", continent: "Europe" },
  { name: "Belgium", capital: "Brussels", flag: "🇧🇪", continent: "Europe" },
  { name: "Belize", capital: "Belmopan", flag: "🇧🇿", continent: "North America" },
  { name: "Benin", capital: "Porto-Novo", flag: "🇧🇯", continent: "Africa" },
  { name: "Bhutan", capital: "Thimphu", flag: "🇧🇹", continent: "Asia" },
  { name: "Bolivia", capital: "Sucre", flag: "🇧🇴", continent: "South America" },
  { name: "Bosnia and Herzegovina", capital: "Sarajevo", flag: "🇧🇦", continent: "Europe" },
  { name: "Botswana", capital: "Gaborone", flag: "🇧🇼", continent: "Africa" },
  { name: "Brazil", capital: "Brasília", flag: "🇧🇷", continent: "South America" },
  { name: "Brunei", capital: "Bandar Seri Begawan", flag: "🇧🇳", continent: "Asia" },
  { name: "Bulgaria", capital: "Sofia", flag: "🇧🇬", continent: "Europe" },
  { name: "Burkina Faso", capital: "Ouagadougou", flag: "🇧🇫", continent: "Africa" },
  { name: "Burundi", capital: "Gitega", flag: "🇧🇮", continent: "Africa" },
  { name: "Cabo Verde", capital: "Praia", flag: "🇨🇻", continent: "Africa" },
  { name: "Cambodia", capital: "Phnom Penh", flag: "🇰🇭", continent: "Asia" },
  { name: "Cameroon", capital: "Yaoundé", flag: "🇨🇲", continent: "Africa" },
  { name: "Canada", capital: "Ottawa", flag: "🇨🇦", continent: "North America" },
  { name: "Central African Republic", capital: "Bangui", flag: "🇨🇫", continent: "Africa" },
  { name: "Chad", capital: "N'Djamena", flag: "🇹🇩", continent: "Africa" },
  { name: "Chile", capital: "Santiago", flag: "🇨🇱", continent: "South America" },
  { name: "China", capital: "Beijing", flag: "🇨🇳", continent: "Asia" },
  { name: "Colombia", capital: "Bogotá", flag: "🇨🇴", continent: "South America" },
  { name: "Comoros", capital: "Moroni", flag: "🇰🇲", continent: "Africa" },
  { name: "Congo, Democratic Republic", capital: "Kinshasa", flag: "🇨🇩", continent: "Africa" },
  { name: "Congo, Republic", capital: "Brazzaville", flag: "🇨🇬", continent: "Africa" },
  { name: "Costa Rica", capital: "San José", flag: "🇨🇷", continent: "North America" },
  { name: "Croatia", capital: "Zagreb", flag: "🇭🇷", continent: "Europe" },
  { name: "Cuba", capital: "Havana", flag: "🇨🇺", continent: "North America" },
  { name: "Cyprus", capital: "Nicosia", flag: "🇨🇾", continent: "Europe" },
  { name: "Czechia", capital: "Prague", flag: "🇨🇿", continent: "Europe" },
  { name: "Denmark", capital: "Copenhagen", flag: "🇩🇰", continent: "Europe" },
  { name: "Djibouti", capital: "Djibouti", flag: "🇩🇯", continent: "Africa" },
  { name: "Dominica", capital: "Roseau", flag: "🇩🇲", continent: "North America" },
  { name: "Dominican Republic", capital: "Santo Domingo", flag: "🇩🇴", continent: "North America" },
  { name: "Ecuador", capital: "Quito", flag: "🇪🇨", continent: "South America" },
  { name: "Egypt", capital: "Cairo", flag: "🇪🇬", continent: "Africa" },
  { name: "El Salvador", capital: "San Salvador", flag: "🇸🇻", continent: "North America" },
  { name: "Equatorial Guinea", capital: "Malabo", flag: "🇬🇶", continent: "Africa" },
  { name: "Eritrea", capital: "Asmara", flag: "🇪🇷", continent: "Africa" },
  { name: "Estonia", capital: "Tallinn", flag: "🇪🇪", continent: "Europe" },
  { name: "Eswatini", capital: "Mbabane", flag: "🇸🇿", continent: "Africa" },
  { name: "Ethiopia", capital: "Addis Ababa", flag: "🇪🇹", continent: "Africa" },
  { name: "Fiji", capital: "Suva", flag: "🇫🇯", continent: "Oceania" },
  { name: "Finland", capital: "Helsinki", flag: "🇫🇮", continent: "Europe" },
  { name: "France", capital: "Paris", flag: "🇫🇷", continent: "Europe" },
  { name: "Gabon", capital: "Libreville", flag: "🇬🇦", continent: "Africa" },
  { name: "Gambia", capital: "Banjul", flag: "🇬🇲", continent: "Africa" },
  { name: "Georgia", capital: "Tbilisi", flag: "🇬🇪", continent: "Asia" },
  { name: "Germany", capital: "Berlin", flag: "🇩🇪", continent: "Europe" },
  { name: "Ghana", capital: "Accra", flag: "🇬🇭", continent: "Africa" },
  { name: "Greece", capital: "Athens", flag: "🇬🇷", continent: "Europe" },
  { name: "Grenada", capital: "St. George's", flag: "🇬🇩", continent: "North America" },
  { name: "Guatemala", capital: "Guatemala City", flag: "🇬🇹", continent: "North America" },
  { name: "Guinea", capital: "Conakry", flag: "🇬🇳", continent: "Africa" },
  { name: "Guinea-Bissau", capital: "Bissau", flag: "🇬🇼", continent: "Africa" },
  { name: "Guyana", capital: "Georgetown", flag: "🇬🇾", continent: "South America" },
  { name: "Haiti", capital: "Port-au-Prince", flag: "🇭🇹", continent: "North America" },
  { name: "Honduras", capital: "Tegucigalpa", flag: "🇭🇳", continent: "North America" },
  { name: "Hungary", capital: "Budapest", flag: "🇭🇺", continent: "Europe" },
  { name: "Iceland", capital: "Reykjavik", flag: "🇮🇸", continent: "Europe" },
  { name: "India", capital: "New Delhi", flag: "🇮🇳", continent: "Asia" },
  { name: "Indonesia", capital: "Jakarta", flag: "🇮🇩", continent: "Asia" },
  { name: "Iran", capital: "Tehran", flag: "🇮🇷", continent: "Asia" },
  { name: "Iraq", capital: "Baghdad", flag: "🇮🇶", continent: "Asia" },
  { name: "Ireland", capital: "Dublin", flag: "🇮🇪", continent: "Europe" },
  { name: "Israel", capital: "Jerusalem", flag: "🇮🇱", continent: "Asia" },
  { name: "Italy", capital: "Rome", flag: "🇮🇹", continent: "Europe" },
  { name: "Jamaica", capital: "Kingston", flag: "🇯🇲", continent: "North America" },
  { name: "Japan", capital: "Tokyo", flag: "🇯🇵", continent: "Asia" },
  { name: "Jordan", capital: "Amman", flag: "🇯🇴", continent: "Asia" },
  { name: "Kazakhstan", capital: "Astana", flag: "🇰🇿", continent: "Asia" },
  { name: "Kenya", capital: "Nairobi", flag: "🇰🇪", continent: "Africa" },
  { name: "Kiribati", capital: "Tarawa", flag: "🇰🇮", continent: "Oceania" },
  { name: "Korea, North", capital: "Pyongyang", flag: "🇰🇵", continent: "Asia" },
  { name: "Korea, South", capital: "Seoul", flag: "🇰🇷", continent: "Asia" },
  { name: "Kosovo", capital: "Pristina", flag: "🇽🇰", continent: "Europe" },
  { name: "Kuwait", capital: "Kuwait City", flag: "🇰🇼", continent: "Asia" },
  { name: "Kyrgyzstan", capital: "Bishkek", flag: "🇰🇬", continent: "Asia" },
  { name: "Laos", capital: "Vientiane", flag: "🇱🇦", continent: "Asia" },
  { name: "Latvia", capital: "Riga", flag: "🇱🇻", continent: "Europe" },
  { name: "Lebanon", capital: "Beirut", flag: "🇱🇧", continent: "Asia" },
  { name: "Lesotho", capital: "Maseru", flag: "🇱🇸", continent: "Africa" },
  { name: "Liberia", capital: "Monrovia", flag: "🇱🇷", continent: "Africa" },
  { name: "Libya", capital: "Tripoli", flag: "🇱🇾", continent: "Africa" },
  { name: "Liechtenstein", capital: "Vaduz", flag: "🇱🇮", continent: "Europe" },
  { name: "Lithuania", capital: "Vilnius", flag: "🇱🇹", continent: "Europe" },
  { name: "Luxembourg", capital: "Luxembourg", flag: "🇱🇺", continent: "Europe" },
  { name: "Madagascar", capital: "Antananarivo", flag: "🇲🇬", continent: "Africa" },
  { name: "Malawi", capital: "Lilongwe", flag: "🇲🇼", continent: "Africa" },
  { name: "Malaysia", capital: "Kuala Lumpur", flag: "🇲🇾", continent: "Asia" },
  { name: "Maldives", capital: "Malé", flag: "🇲🇻", continent: "Asia" },
  { name: "Mali", capital: "Bamako", flag: "🇲🇱", continent: "Africa" },
  { name: "Malta", capital: "Valletta", flag: "🇲🇹", continent: "Europe" },
  { name: "Marshall Islands", capital: "Majuro", flag: "🇲🇭", continent: "Oceania" },
  { name: "Mauritania", capital: "Nouakchott", flag: "🇲🇷", continent: "Africa" },
  { name: "Mauritius", capital: "Port Louis", flag: "🇲🇺", continent: "Africa" },
  { name: "Mexico", capital: "Mexico City", flag: "🇲🇽", continent: "North America" },
  { name: "Micronesia", capital: "Palikir", flag: "🇫🇲", continent: "Oceania" },
  { name: "Moldova", capital: "Chisinau", flag: "🇲🇩", continent: "Europe" },
  { name: "Monaco", capital: "Monaco", flag: "🇲🇨", continent: "Europe" },
  { name: "Mongolia", capital: "Ulaanbaatar", flag: "🇲🇳", continent: "Asia" },
  { name: "Montenegro", capital: "Podgorica", flag: "🇲🇪", continent: "Europe" },
  { name: "Morocco", capital: "Rabat", flag: "🇲🇦", continent: "Africa" },
  { name: "Mozambique", capital: "Maputo", flag: "🇲🇿", continent: "Africa" },
  { name: "Myanmar", capital: "Naypyidaw", flag: "🇲🇲", continent: "Asia" },
  { name: "Namibia", capital: "Windhoek", flag: "🇳🇦", continent: "Africa" },
  { name: "Nauru", capital: "Yaren", flag: "🇳🇷", continent: "Oceania" },
  { name: "Nepal", capital: "Kathmandu", flag: "🇳🇵", continent: "Asia" },
  { name: "Netherlands", capital: "Amsterdam", flag: "🇳🇱", continent: "Europe" },
  { name: "New Zealand", capital: "Wellington", flag: "🇳🇿", continent: "Oceania" },
  { name: "Nicaragua", capital: "Managua", flag: "🇳🇮", continent: "North America" },
  { name: "Niger", capital: "Niamey", flag: "🇳🇪", continent: "Africa" },
  { name: "Nigeria", capital: "Abuja", flag: "🇳🇬", continent: "Africa" },
  { name: "North Macedonia", capital: "Skopje", flag: "🇲🇰", continent: "Europe" },
  { name: "Norway", capital: "Oslo", flag: "🇳🇴", continent: "Europe" },
  { name: "Oman", capital: "Muscat", flag: "🇴🇲", continent: "Asia" },
  { name: "Pakistan", capital: "Islamabad", flag: "🇵🇰", continent: "Asia" },
  { name: "Palau", capital: "Ngerulmud", flag: "🇵🇼", continent: "Oceania" },
  { name: "Palestine", capital: "Ramallah", flag: "🇵🇸", continent: "Asia" },
  { name: "Panama", capital: "Panama City", flag: "🇵🇦", continent: "North America" },
  { name: "Papua New Guinea", capital: "Port Moresby", flag: "🇵🇬", continent: "Oceania" },
  { name: "Paraguay", capital: "Asunción", flag: "🇵🇾", continent: "South America" },
  { name: "Peru", capital: "Lima", flag: "🇵🇪", continent: "South America" },
  { name: "Philippines", capital: "Manila", flag: "🇵🇭", continent: "Asia" },
  { name: "Poland", capital: "Warsaw", flag: "🇵🇱", continent: "Europe" },
  { name: "Portugal", capital: "Lisbon", flag: "🇵🇹", continent: "Europe" },
  { name: "Qatar", capital: "Doha", flag: "🇶🇦", continent: "Asia" },
  { name: "Romania", capital: "Bucharest", flag: "🇷🇴", continent: "Europe" },
  { name: "Russia", capital: "Moscow", flag: "🇷🇺", continent: "Europe/Asia" },
  { name: "Rwanda", capital: "Kigali", flag: "🇷🇼", continent: "Africa" },
  { name: "Saint Kitts and Nevis", capital: "Basseterre", flag: "🇰🇳", continent: "North America" },
  { name: "Saint Lucia", capital: "Castries", flag: "🇱🇨", continent: "North America" },
  { name: "Saint Vincent and the Grenadines", capital: "Kingstown", flag: "🇻🇨", continent: "North America" },
  { name: "Samoa", capital: "Apia", flag: "🇼🇸", continent: "Oceania" },
  { name: "San Marino", capital: "San Marino", flag: "🇸🇲", continent: "Europe" },
  { name: "Sao Tome and Principe", capital: "São Tomé", flag: "🇸🇹", continent: "Africa" },
  { name: "Saudi Arabia", capital: "Riyadh", flag: "🇸🇦", continent: "Asia" },
  { name: "Senegal", capital: "Dakar", flag: "🇸🇳", continent: "Africa" },
  { name: "Serbia", capital: "Belgrade", flag: "🇷🇸", continent: "Europe" },
  { name: "Seychelles", capital: "Victoria", flag: "🇸🇨", continent: "Africa" },
  { name: "Sierra Leone", capital: "Freetown", flag: "🇸🇱", continent: "Africa" },
  { name: "Singapore", capital: "Singapore", flag: "🇸🇬", continent: "Asia" },
  { name: "Slovakia", capital: "Bratislava", flag: "🇸🇰", continent: "Europe" },
  { name: "Slovenia", capital: "Ljubljana", flag: "🇸🇮", continent: "Europe" },
  { name: "Solomon Islands", capital: "Honiara", flag: "🇸🇧", continent: "Oceania" },
  { name: "Somalia", capital: "Mogadishu", flag: "🇸🇴", continent: "Africa" },
  { name: "South Africa", capital: "Pretoria", flag: "🇿🇦", continent: "Africa" },
  { name: "South Sudan", capital: "Juba", flag: "🇸🇸", continent: "Africa" },
  { name: "Spain", capital: "Madrid", flag: "🇪🇸", continent: "Europe" },
  { name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag: "🇱🇰", continent: "Asia" },
  { name: "Sudan", capital: "Khartoum", flag: "🇸🇩", continent: "Africa" },
  { name: "Suriname", capital: "Paramaribo", flag: "🇸🇷", continent: "South America" },
  { name: "Sweden", capital: "Stockholm", flag: "🇸🇪", continent: "Europe" },
  { name: "Switzerland", capital: "Bern", flag: "🇨🇭", continent: "Europe" },
  { name: "Syria", capital: "Damascus", flag: "🇸🇾", continent: "Asia" },
  { name: "Taiwan", capital: "Taipei", flag: "🇹🇼", continent: "Asia" },
  { name: "Tajikistan", capital: "Dushanbe", flag: "🇹🇯", continent: "Asia" },
  { name: "Tanzania", capital: "Dodoma", flag: "🇹🇿", continent: "Africa" },
  { name: "Thailand", capital: "Bangkok", flag: "🇹🇭", continent: "Asia" },
  { name: "Timor-Leste", capital: "Dili", flag: "🇹🇱", continent: "Asia" },
  { name: "Togo", capital: "Lomé", flag: "🇹🇬", continent: "Africa" },
  { name: "Tonga", capital: "Nukuʻalofa", flag: "🇹🇴", continent: "Oceania" },
  { name: "Trinidad and Tobago", capital: "Port of Spain", flag: "🇹🇹", continent: "North America" },
  { name: "Tunisia", capital: "Tunis", flag: "🇹🇳", continent: "Africa" },
  { name: "Turkey", capital: "Ankara", flag: "🇹🇷", continent: "Asia/Europe" },
  { name: "Turkmenistan", capital: "Ashgabat", flag: "🇹🇲", continent: "Asia" },
  { name: "Tuvalu", capital: "Funafuti", flag: "🇹🇻", continent: "Oceania" },
  { name: "Uganda", capital: "Kampala", flag: "🇺🇬", continent: "Africa" },
  { name: "Ukraine", capital: "Kyiv", flag: "🇺🇦", continent: "Europe" },
  { name: "United Arab Emirates", capital: "Abu Dhabi", flag: "🇦🇪", continent: "Asia" },
  { name: "United Kingdom", capital: "London", flag: "🇬🇧", continent: "Europe" },
  { name: "United States", capital: "Washington, D.C.", flag: "🇺🇸", continent: "North America" },
  { name: "Uruguay", capital: "Montevideo", flag: "🇺🇾", continent: "South America" },
  { name: "Uzbekistan", capital: "Tashkent", flag: "🇺🇿", continent: "Asia" },
  { name: "Vanuatu", capital: "Port Vila", flag: "🇻🇺", continent: "Oceania" },
  { name: "Vatican City", capital: "Vatican City", flag: "🇻🇦", continent: "Europe" },
  { name: "Venezuela", capital: "Caracas", flag: "🇻🇪", continent: "South America" },
  { name: "Vietnam", capital: "Hanoi", flag: "🇻🇳", continent: "Asia" },
  { name: "Yemen", capital: "Sana'a", flag: "🇾🇪", continent: "Asia" },
  { name: "Zambia", capital: "Lusaka", flag: "🇿🇲", continent: "Africa" },
  { name: "Zimbabwe", capital: "Harare", flag: "🇿🇼", continent: "Africa" }
];